
namespace ManagedVulkan {

	public ref class Vulkan
	{
	public:
		vkCreateInstance  
		vkDestroyInstance  
		vkEnumeratePhysicalDevices  
		vkGetDeviceProcAddr  
		vkGetInstanceProcAddr  
		vkGetPhysicalDeviceProperties  
		vkGetPhysicalDeviceQueueFamilyProperties  
		vkGetPhysicalDeviceMemoryProperties  
		vkGetPhysicalDeviceFeatures  
		vkGetPhysicalDeviceFormatProperties  
		vkGetPhysicalDeviceImageFormatProperties  
		vkCreateDevice  
		vkDestroyDevice  
		vkEnumerateInstanceLayerProperties  
		vkEnumerateInstanceExtensionProperties  
		vkEnumerateDeviceLayerProperties  
		vkEnumerateDeviceExtensionProperties  
		vkGetDeviceQueue  
		vkQueueSubmit  
		vkQueueWaitIdle  
		vkDeviceWaitIdle  
		vkAllocateMemory  
		vkFreeMemory  
		vkMapMemory  
		vkUnmapMemory  
		vkFlushMappedMemoryRanges  
		vkInvalidateMappedMemoryRanges  
		vkGetDeviceMemoryCommitment  
		vkGetBufferMemoryRequirements  
		vkBindBufferMemory  
		vkGetImageMemoryRequirements  
		vkBindImageMemory  
		vkGetImageSparseMemoryRequirements  
		vkGetPhysicalDeviceSparseImageFormatProperties  
		vkQueueBindSparse  
		vkCreateFence  
		vkDestroyFence  
		vkResetFences  
		vkGetFenceStatus  
		vkWaitForFences  
		vkCreateSemaphore  
		vkDestroySemaphore  
		vkCreateEvent  
		vkDestroyEvent  
		vkGetEventStatus  
		vkSetEvent  
		vkResetEvent  
		vkCreateQueryPool  
		vkDestroyQueryPool  
		vkGetQueryPoolResults  
		vkCreateBuffer  
		vkDestroyBuffer  
		vkCreateBufferView  
		vkDestroyBufferView  
		vkCreateImage  
		vkDestroyImage  
		vkGetImageSubresourceLayout  
		vkCreateImageView  
		vkDestroyImageView  
		vkCreateShaderModule  
		vkDestroyShaderModule  
		vkCreatePipelineCache  
		vkDestroyPipelineCache  
		vkGetPipelineCacheData  
		vkMergePipelineCaches  
		vkCreateGraphicsPipelines  
		vkCreateComputePipelines  
		vkDestroyPipeline  
		vkCreatePipelineLayout  
		vkDestroyPipelineLayout  
		vkCreateSampler  
		vkDestroySampler  
		vkCreateDescriptorSetLayout  
		vkDestroyDescriptorSetLayout  
		vkCreateDescriptorPool  
		vkDestroyDescriptorPool  
		vkResetDescriptorPool  
		vkAllocateDescriptorSets  
		vkFreeDescriptorSets  
		vkUpdateDescriptorSets  
		vkCreateFramebuffer  
		vkDestroyFramebuffer  
		vkCreateRenderPass  
		vkDestroyRenderPass  
		vkGetRenderAreaGranularity  
		vkCreateCommandPool  
		vkDestroyCommandPool  
		vkResetCommandPool  
		vkAllocateCommandBuffers  
		vkFreeCommandBuffers  
		vkBeginCommandBuffer  
		vkEndCommandBuffer  
		vkResetCommandBuffer  
		vkCmdBindPipeline  
		vkCmdSetViewport  
		vkCmdSetScissor  
		vkCmdSetLineWidth  
		vkCmdSetDepthBias  
		vkCmdSetBlendConstants  
		vkCmdSetDepthBounds  
		vkCmdSetStencilCompareMask  
		vkCmdSetStencilWriteMask  
		vkCmdSetStencilReference  
		vkCmdBindDescriptorSets  
		vkCmdBindIndexBuffer  
		vkCmdBindVertexBuffers  
		vkCmdDraw  
		vkCmdDrawIndexed  
		vkCmdDrawIndirect  
		vkCmdDrawIndexedIndirect  
		vkCmdDispatch  
		vkCmdDispatchIndirect  
		vkCmdCopyBuffer  
		vkCmdCopyImage  
		vkCmdBlitImage  
		vkCmdCopyBufferToImage  
		vkCmdCopyImageToBuffer  
		vkCmdUpdateBuffer  
		vkCmdFillBuffer  
		vkCmdClearColorImage  
		vkCmdClearDepthStencilImage  
		vkCmdClearAttachments  
		vkCmdResolveImage  
		vkCmdSetEvent  
		vkCmdResetEvent  
		vkCmdWaitEvents  
		vkCmdPipelineBarrier  
		vkCmdBeginQuery  
		vkCmdEndQuery  
		vkCmdResetQueryPool  
		vkCmdWriteTimestamp  
		vkCmdCopyQueryPoolResults  
		vkCmdPushConstants  
		vkCmdBeginRenderPass  
		vkCmdNextSubpass  
		vkCmdEndRenderPass  
		vkCmdExecuteCommands  
		vkCreateAndroidSurfaceKHR  
		vkGetPhysicalDeviceDisplayPropertiesKHR  
		vkGetPhysicalDeviceDisplayPlanePropertiesKHR  
		vkGetDisplayPlaneSupportedDisplaysKHR  
		vkGetDisplayModePropertiesKHR  
		vkCreateDisplayModeKHR  
		vkGetDisplayPlaneCapabilitiesKHR  
		vkCreateDisplayPlaneSurfaceKHR  
		vkCreateSharedSwapchainsKHR  
		vkCreateMirSurfaceKHR  
		vkGetPhysicalDeviceMirPresentationSupportKHR  
		vkDestroySurfaceKHR  
		vkGetPhysicalDeviceSurfaceSupportKHR  
		vkGetPhysicalDeviceSurfaceCapabilitiesKHR  
		vkGetPhysicalDeviceSurfaceFormatsKHR  
		vkGetPhysicalDeviceSurfacePresentModesKHR  
		vkCreateSwapchainKHR  
		vkDestroySwapchainKHR  
		vkGetSwapchainImagesKHR  
		vkAcquireNextImageKHR  
		vkQueuePresentKHR  
		vkCreateWaylandSurfaceKHR  
		vkGetPhysicalDeviceWaylandPresentationSupportKHR  
		vkCreateWin32SurfaceKHR  
		vkGetPhysicalDeviceWin32PresentationSupportKHR  
		vkCreateXlibSurfaceKHR  
		vkGetPhysicalDeviceXlibPresentationSupportKHR  
		vkCreateXcbSurfaceKHR  
		vkGetPhysicalDeviceXcbPresentationSupportKHR  
		vkCreateDebugReportCallbackEXT  
		vkDestroyDebugReportCallbackEXT  
		vkDebugReportMessageEXT  
	}
}